import type { ChannelMessageThread } from "@/lib/work-messages";

const LONG_RUNBOOK = [
  "Deployment runbook — ACME SMB demo environment",
  "",
  "1. Pre-flight checks",
  "   • Confirm staging URL resolves and TLS certificate is valid.",
  "   • Verify LiNKaios module registry shows linksites@1.2.0 as active.",
  "   • Run smoke test suite against /api/health and /api/modules/linksites/status.",
  "",
  "2. Database migration",
  "   • Apply pending Supabase migrations in order (20260518_linksites_preview.sql through 20260520_audit_indexes.sql).",
  "   • Backfill tenant_id on any legacy rows in channel_message_links.",
  "   • Rebuild materialized view mv_thread_activity if migration 20260519 is present.",
  "",
  "3. Application rollout",
  "   • Deploy linkaios-web to staging slot B; wait for health check green.",
  "   • Flip traffic from slot A → B via Caddy upstream weight change.",
  "   • Confirm LiNKbrain event ingestion receives deployment.completed within 60 seconds.",
  "",
  "4. Post-deploy validation",
  "   • Open WebsiteFactory lead-to-preview flow end-to-end with seed lead CSV row #7.",
  "   • Confirm Plane task PLANE-1042 reflects QA assignment.",
  "   • Capture screenshot of preview site and attach to project audit bundle.",
  "",
  "5. Rollback criteria",
  "   • Any 5xx on /work/messages or /projects for more than 2 consecutive minutes.",
  "   • Zulip webhook delivery failures exceeding 3 in a 10-minute window.",
  "   • LiNKbrain write latency p95 above 800ms for 5 minutes.",
  "",
  "6. Sign-off",
  "   • OpsBot-2 posts summary to #ops-deploys.",
  "   • Principal receives briefing card in LiNKaios Overview.",
  "   • Mark project demo-smb stage as complete once stakeholder walkthrough is scheduled.",
].join("\n");

export const DEMO_CHANNEL_THREADS: ChannelMessageThread[] = [
  {
    id: "demo-channel-ops",
    channel: "Zulip",
    channelTag: "Zulip",
    projectName: "LiNKaios Rollout",
    subject: "ops · deployment hand-off",
    preview: "SalesBot-1: Site preview is live at the staging URL. Routing check complete.",
    lastActivity: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    detail: [
      "SalesBot-1 · 08:47\nSubject: Rollout complete — staging preview live\nHi team — LiNKaios module rollout is complete for the ACME SMB demo. Site preview is live at the staging URL. Routing check passed ✓",
      "OpsBot-2 · 08:52\nSubject: Plane task created for QA\nReceived. I've created a Plane task for the QA verification step and assigned it to LinkReviewer-1. Task ID: PLANE-1042.",
      "Alex (operator) · 09:01\nSubject: Stakeholder walkthrough\nGood. Can we schedule the stakeholder walkthrough for Thursday at 3 PM? Add to the Plane task.",
      "SalesBot-1 · 09:03\nConfirmed. Calendar invite sent to stakeholders. Plane task PLANE-1042 updated with the Thursday 15:00 slot. No further actions pending from my side.",
      "OpsBot-2 · 09:15\nSubject: Full deployment runbook\n" + LONG_RUNBOOK,
      "LinkReviewer-1 · 09:22\nSubject: QA checklist started\nStarting QA pass on staging preview. Will report blockers in this thread.",
      "SalesBot-1 · 09:28\nSubject: Preview assets refreshed\nUpdated hero copy and favicon on staging. Re-run visual diff when ready.",
      "Alex (operator) · 09:35\nThanks — please keep the thread updated as QA progresses.",
    ].join("\n---\n"),
    missionId: "demo-smb",
    messageCount: 8,
    messages: [],
    streamId: 42,
    topic: "deployment hand-off",
    hasUnread: true,
    openHref: "/settings/platform",
  },
  {
    id: "demo-channel-support",
    channel: "Zulip",
    channelTag: "Zulip",
    projectName: "Brightfield Co. Onboarding",
    subject: "support · customer intake",
    preview: "SupportBot-3: Intake form received from Brightfield Co. SLA clock started.",
    lastActivity: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    detail: [
      "SupportBot-3 · 06:14\nSubject: New intake — ticket #2091\nIntake form received from Brightfield Co. via the website widget. SLA clock started. Ticket #2091 created. Priority: High.",
      "Maya (operator) · 06:30\nSubject: Assignment\nAssign to LiNKbot-Support and flag for human review if no resolution within 4 hours.",
      "LiNKbot-Support · 06:45\nSubject: Initial triage complete\nClassified as onboarding configuration issue. Requested CRM capability credentials from tenant admin.",
      "SupportBot-3 · 07:02\nCredentials received. Running capability lease for chatwoot.sync_contact (dry-run mode).",
      "Maya (operator) · 07:18\nApproved dry-run. Proceed to live sync once audit hook confirms.",
    ].join("\n---\n"),
    missionId: "demo-ai-edu",
    messageCount: 5,
    messages: [],
    streamId: 55,
    topic: "customer intake",
    hasUnread: false,
    openHref: "/settings/platform",
  },
  {
    id: "demo-channel-qa",
    channel: "Zulip",
    channelTag: "Zulip",
    projectName: "WebsiteFactory MVO",
    subject: "qa · preview regression",
    preview: "LinkReviewer-1: Visual diff flagged hero spacing on mobile.",
    lastActivity: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    detail: [
      "LinkReviewer-1 · 07:40\nSubject: Mobile hero spacing\nVisual diff flagged 12px spacing drift on mobile hero between template v3 and v4.",
      "DesignBot-4 · 07:55\nSubject: Fix pushed\nPushed token update to spacing.scale.sm in linksites theme. Ready for re-run.",
      "LinkReviewer-1 · 08:10\nRe-run passed on iPhone 14 viewport. Closing regression item.",
    ].join("\n---\n"),
    missionId: "demo-smb",
    messageCount: 3,
    messages: [],
    streamId: 61,
    topic: "preview regression",
    hasUnread: true,
    openHref: "/settings/platform",
  },
  {
    id: "demo-channel-briefing",
    channel: "Zulip",
    channelTag: "Zulip",
    projectName: "Principal Briefings",
    subject: "briefings · weekly digest",
    preview: "BriefingBot: Week 20 summary ready for review.",
    lastActivity: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    detail: [
      "BriefingBot · 16:00\nSubject: Week 20 digest draft\nWeek 20 summary ready for review. Three projects advanced, one blocked on Zulip credentials.",
      "Alex (operator) · 16:22\nSubject: Approved with edits\nApproved with minor edits to project priorities section.",
    ].join("\n---\n"),
    missionId: "demo-smb",
    messageCount: 2,
    messages: [],
    streamId: 72,
    topic: "weekly digest",
    hasUnread: false,
    openHref: "/settings/platform",
  },
  {
    id: "demo-channel-infra",
    channel: "Zulip",
    channelTag: "Zulip",
    projectName: "Platform Infra",
    subject: "infra · certificate rotation",
    preview: "InfraBot: Staging TLS cert renewed; expiry now 2027-05-01.",
    lastActivity: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    detail: [
      "InfraBot · 04:10\nSubject: TLS renewal complete\nStaging TLS cert renewed; expiry now 2027-05-01. No downtime observed.",
      "OpsBot-2 · 04:25\nLogged to LiNKbrain audit. Monitoring alerts cleared.",
    ].join("\n---\n"),
    messageCount: 2,
    messages: [],
    streamId: 88,
    topic: "certificate rotation",
    hasUnread: false,
    openHref: "/settings/platform",
  },
  {
    id: "demo-channel-slack",
    channel: "Slack",
    channelTag: "Slack",
    projectName: "Platform Infra",
    subject: "eng-deploys · staging cutover",
    preview: "Fixture Slack-style thread for multi-channel layout.",
    lastActivity: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    detail: [
      "DeployBot · 09:20\nSubject: Cutover started\nStaging cutover initiated. ETA 8 minutes.",
      "DeployBot · 09:28\nSubject: Cutover complete\nStaging cutover complete. All health checks green ✓",
      "DeployBot · 09:35\nPost-deploy metrics within baseline. Handing off to on-call.",
    ].join("\n---\n"),
    messageCount: 3,
    messages: [],
    hasUnread: true,
    openHref: "/settings/platform",
  },
];
